### PR TITLE
Add a license

### PR DESCRIPTION
**Pull request by liontiger23**
I propose adding a license that reflects the spirit and intentions of the project, such as Apache 2.0 license (which is currently the license of Scala).
This will greatly help others (companies and individuals) with using and contributing to this project.
Thanks in advance!

### CODE REVIEW

**Comment by liontiger23** [comment]
Note that you should update the license after appendix:
```
   APPENDIX: How to apply the Apache License to your work.

      To apply the Apache License to your work, attach the following
      boilerplate notice, with the fields enclosed by brackets "[]"
      replaced with your own identifying information. (Don't include
      the brackets!)  The text should be enclosed in the appropriate
      comment syntax for the file format. We also recommend that a
      file or class name and description of purpose be included on the
      same "printed page" as the copyright notice for easier
      identification within third-party archives.

   Copyright [yyyy] [name of copyright owner]
```

**Comment by SethTisue** [comment]
since the code comes from the scala/scala repo, which is Apache 2 licensed, I agree that the Apache 2 license is the right choice here

**Comment by liontiger23** [comment]
@SethTisue Do we actually need to update the license with year and copyright owner, or will the unedited Apache 2.0 license suffice? I'm asking, because I noticed that scala/scala has Apache license template as-is with appendix and `Copyright [yyyy] [name of copyright owner]`, but has `NOTICE` file alongside it.

**Comment by SethTisue** [comment]
The unedited Apache 2.0 license suffices. You're supposed to leave it unedited, and any repo-specific stuff goes in NOTICE and/or in individual source files.

**Pull request merged**
